---

num_rounds: 4
num_clients: 1
batch_size: 10
num_classes: 1
num_clients_per_round_fit: 1
num_clients_per_round_eval: 1
config_fit: 
  lr: 0.01
  momentum: 0.9
  weight_decay: 0.0001
  local_epochs: 1
patience: 25
output_size: 224


  
defaults:
  - strategy: fedavg
  - model: vmunet-v2