---
_target_: train.TrainTestPipe
img_dim: 224
in_channels: 3
out_channels: 128
head_num: 4
mlp_dim: 256
block_num: 8
patch_dim: 16
class_num: 1
lr: 0.01
epochs: 1
patience: 3
momentum: 0.9
weight_decay: 0.0001
model_path: '/content/drive/MyDrive/kvasir/model/model_v2_sgd.pth'