---
network: 'vmunet-v2'
model_config:
  _target_: vmunet_v2.VMUNetV2
  num_classes: 1
  input_channels: 3
  depths: [2,2,9,2]
  depths_decoder: [2,2,2,1]
  drop_path_rate: 0.2
  load_ckpt_path: '/content/drive/MyDrive/kvasir/pretrained_model_for_vmamba/upernet_vssm_4xb4-160k_ade20k-512x512_small_iter_144000.pth'
  # /content/drive/MyDrive/kvasir/pretrained_model_for_vmamba/upernet_vssm_4xb4-160k_ade20k-512x512_tiny_s_iter_160000.pth
  deep_supervision: True

distributed : False
local_rank : -1
num_workers : 8
seed : 42
world_size : None
rank: None
amp: False
gpu_id: '2'
batch_size: 10
epochs: 300
input_size_h: 224
input_size_w: 224

print_interval : 20
val_interval : 1
save_interval : 10
threshold : 0.5

criterion:
  _target_: utils_vmunet.BceDiceLoss
  wb: 1
  wd: 1

opt: 'AdamW'
lr: 0.0001
weight_decay: 0.01
eps: 0.00000001
betas: [0.9, 0.999]
amsgrad: False

sch: 'CosineAnnealingLR'
T_max: 50
eta_min: 0.00001
last_epoch: -1